export const Channels = [
  {
    title: "Team Global Express",
    id: 22,
    data_link: "",
    href: '/tge',
    active: true,
  },
  {
    title: "mycar - Tyre & Auto",
    id: 1,
    data_link: "",
    href: '/mycar',
    active: false,
  },
  {
    title: "Telstra Assurance/Faults",
    id: 2,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "IAG RIA Property",
    id: 3,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "IAG Sales & Service",
    id: 4,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "IAG New Zealand",
    id: 5,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Telstra Inbound Sales",
    id: 6,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Telstra Digital (PH)",
    id: 7,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Telstra Service",
    id: 8,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Telstra Business Inbound",
    id: 9,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "OneNZ Business (PH)",
    id: 10,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "OneNZ V&M (PH)",
    id: 11,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "OneNZ Telesales (PH)",
    id: 12,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "AirNZ (AU & PH)",
    id: 13,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Amplifon",
    id: 14,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "HCF",
    id: 15,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "iMED",
    id: 16,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "AUSPOST",
    id: 17,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Voyages",
    id: 18,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "VGA (AU & PH)",
    id: 19,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Electrolux (PH)",
    id: 20,
    data_link: "",
    href: '/',
    active: false,
  },
  {
    title: "Services Australia",
    id: 21,
    data_link: "",
    href: '/',
    active: false,
  },
];
